<?php

use App\Http\Controllers\AcademicSetupController;
use App\Http\Controllers\AmalKhairController;
use App\Http\Controllers\AssessmentController;
use App\Http\Controllers\AssessmentPageController;
use App\Http\Controllers\AssignmentController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AttendancePageController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\CharacterAssessmentController;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EnrollmentController;
use App\Http\Controllers\LicenseController;
use App\Http\Controllers\LicensePageController;
use App\Http\Controllers\MarkController;
use App\Http\Controllers\MarkSettingsController;
use App\Http\Controllers\NotificationPageController;
use App\Http\Controllers\ParentAccessController;
use App\Http\Controllers\ParentPortalController;
use App\Http\Controllers\PbdController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ReportPageController;
use App\Http\Controllers\ReportVerificationPageController;
use App\Http\Controllers\RphController;
use App\Http\Controllers\RphPageController;
use App\Http\Controllers\SchoolController;
use App\Http\Controllers\SchoolModuleController;
use App\Http\Controllers\SchoolModulePageController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TakwimController;
use App\Http\Controllers\TakwimPageController;
use App\Http\Controllers\TimetableController;
use App\Http\Controllers\TimetablePageController;
use App\Http\Controllers\UserAdminController;
use App\Http\Controllers\WebAdminController;
use App\Http\Controllers\WorkflowController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Schema;

Route::redirect('/', '/dashboard');
Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
Route::post('/login', [AuthenticatedSessionController::class, 'store'])->name('login.store');
Route::get('/api/public/schools', [SchoolController::class, 'publicIndex'])->name('api.public.schools');
Route::post('/api/auth/forgot-password', [PasswordResetLinkController::class, 'apiStore'])->name('api.auth.forgot-password');
Route::post('/api/auth/reset-password', [NewPasswordController::class, 'apiStore'])->name('api.auth.reset-password');
Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');
Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
Route::post('/reset-password', [NewPasswordController::class, 'store'])->name('password.update');
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->middleware('auth')->name('logout');
Route::get('/change-password', [ChangePasswordController::class, 'create'])->middleware('auth')->name('password.change');
Route::post('/change-password', [ChangePasswordController::class, 'store'])->middleware('auth')->name('password.change.store');

Route::get('/dashboard', DashboardController::class)->middleware('auth')->name('dashboard');
Route::get('/laporan', [ReportPageController::class, 'index'])->middleware('auth')->name('reports.index');
Route::get('/analisis', [ReportPageController::class, 'index'])->middleware('auth')->name('reports.analysis');
Route::get('/takwim', [TakwimPageController::class, 'index'])->middleware('auth')->name('takwim.index');
Route::post('/takwim', [TakwimPageController::class, 'store'])->middleware('auth')->name('takwim.store');
Route::get('/rph', [RphPageController::class, 'index'])->middleware('auth')->name('rph.index');
Route::get('/jadual-waktu', [TimetablePageController::class, 'index'])->middleware('auth')->name('timetable.index');
Route::post('/jadual-waktu/generate', [TimetablePageController::class, 'generateSlots'])->middleware('auth')->name('timetable.generate');

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/schools', [WebAdminController::class, 'schools'])->name('schools');
    Route::get('/classes', [WebAdminController::class, 'classes'])->name('classes');
    Route::get('/students', [WebAdminController::class, 'students'])->name('students');
    Route::post('/schools', [WebAdminController::class, 'storeSchool'])->name('schools.store');
    Route::post('/classes', [WebAdminController::class, 'storeClass'])->name('classes.store');
    Route::post('/students', [WebAdminController::class, 'storeStudent'])->name('students.store');
    Route::get('/licenses', [LicensePageController::class, 'index'])->name('licenses');
    Route::post('/licenses', [LicensePageController::class, 'store'])->name('licenses.store');
    Route::get('/notifications', [NotificationPageController::class, 'index'])->name('notifications');
    Route::post('/notifications/{id}/read', [NotificationPageController::class, 'read'])->name('notifications.read');
    Route::get('/users', [UserAdminController::class, 'index'])->name('users');
    Route::post('/users', [UserAdminController::class, 'store'])->name('users.store');
    Route::get('/school-modules', [SchoolModulePageController::class, 'index'])->name('school-modules');
    Route::post('/school-modules', [SchoolModulePageController::class, 'store'])->name('school-modules.store');
    Route::get('/assessments/psra', [AssessmentPageController::class, 'psra'])->name('assessments.psra');
    Route::get('/assessments/upkk', [AssessmentPageController::class, 'upkk'])->name('assessments.upkk');
    Route::post('/assessments/psra', [AssessmentPageController::class, 'storePsra'])->name('assessments.psra.store');
    Route::post('/assessments/upkk', [AssessmentPageController::class, 'storeUpkk'])->name('assessments.upkk.store');
    Route::get('/attendance', [AttendancePageController::class, 'index'])->name('attendance');
    Route::post('/attendance', [AttendancePageController::class, 'store'])->name('attendance.store');
});

Route::get('/health', function () {
    $started = microtime(true);
    try {
        DB::select('select 1');
        $requiredTables = ['users', 'schools', 'classes', 'students', 'marks', 'daily_attendance', 'takwim_events'];
        $missingTables = array_values(array_filter($requiredTables, fn (string $table): bool => ! Schema::hasTable($table)));
        if ($missingTables) {
            return response()->json(['status' => 'degraded', 'database' => 'connected', 'missingTables' => $missingTables, 'responseTimeMs' => (int) ((microtime(true) - $started) * 1000)], 503);
        }

        return response()->json(['status' => 'ok', 'database' => 'connected', 'schema' => 'ready', 'responseTimeMs' => (int) ((microtime(true) - $started) * 1000)]);
    } catch (Throwable) {
        return response()->json(['status' => 'degraded', 'database' => 'unavailable'], 503);
    }
})->name('health');

Route::middleware('auth')->prefix('api')->group(function () {
    Route::get('/students', [StudentController::class, 'index']);
    Route::get('/students/school-summaries', [StudentController::class, 'schoolSummaries']);
    Route::post('/students', [StudentController::class, 'store']);
    Route::post('/students/upsert', [StudentController::class, 'upsert']);
    Route::post('/students/bulk', [StudentController::class, 'bulkStore']);
    Route::post('/marks', [MarkController::class, 'store']);
    Route::get('/marks', [MarkController::class, 'index']);
    Route::get('/marks/components', [MarkController::class, 'components']);
    Route::get('/subject-components', [MarkController::class, 'componentDefinitions']);
    Route::post('/marks/components', [MarkController::class, 'storeComponents']);
    Route::get('/subjects', [AcademicSetupController::class, 'subjects']);
    Route::get('/subject-grade-rules', [AcademicSetupController::class, 'gradeRules']);
    Route::post('/subjects', [AcademicSetupController::class, 'storeSubject']);
    Route::get('/exams', [AcademicSetupController::class, 'exams']);
    Route::post('/exams', [AcademicSetupController::class, 'storeExam']);
    Route::post('/exams/{id}/access', [AcademicSetupController::class, 'updateExamAccess'])->whereUuid('id');
    Route::get('/reports/students/{studentId}', [ReportController::class, 'student'])->whereUuid('studentId');
    Route::get('/reports/classes/{classId}', [ReportController::class, 'classReport'])->whereUuid('classId');
    Route::get('/reports/individual', [ReportController::class, 'individual']);
    Route::get('/reports/schools', [ReportController::class, 'schoolSummaries']);
    Route::get('/reports/subjects', [ReportController::class, 'subjectSummaries']);
    Route::get('/schools', [SchoolController::class, 'index']);
    Route::get('/dashboard/counts', [DashboardController::class, 'counts']);
    Route::post('/schools/{schoolCode}/zone', [SchoolController::class, 'updateZone']);
    Route::get('/admin/users', [UserAdminController::class, 'apiIndex']);
    Route::post('/admin/users/{userId}/status', [UserAdminController::class, 'apiStatus'])->whereUuid('userId');
    Route::post('/admin/users/{userId}/activate', [UserAdminController::class, 'apiActivate'])->whereUuid('userId');
    Route::post('/admin/users/{userId}', [UserAdminController::class, 'apiUpdate'])->whereUuid('userId');
    Route::post('/admin/users/{userId}/reset-password', [UserAdminController::class, 'apiResetPassword'])->whereUuid('userId');
    Route::post('/schools', [SchoolController::class, 'store']);
    Route::get('/classes', [ClassController::class, 'index']);
    Route::post('/classes', [ClassController::class, 'store']);
    Route::post('/assignments/class-teacher', [AssignmentController::class, 'classTeacher']);
    Route::post('/assignments/subject-teacher', [AssignmentController::class, 'subjectTeacher']);
    Route::post('/assignments/bulk', [AssignmentController::class, 'bulk']);
    Route::get('/assignments', [AssignmentController::class, 'index']);
    Route::post('/attendance', [AttendanceController::class, 'store']);
    Route::get('/attendance/context', [AttendanceController::class, 'context']);
    Route::get('/attendance', [AttendanceController::class, 'index']);
    Route::get('/takwim', [TakwimController::class, 'index']);
    Route::post('/takwim', [TakwimController::class, 'store']);
    Route::post('/pbd/assessments', [PbdController::class, 'storeAssessment']);
    Route::get('/pbd/marks', [PbdController::class, 'index']);
    Route::post('/pbd/assessments/{assessmentId}/marks', [PbdController::class, 'storeMarks'])->whereUuid('assessmentId');
    Route::get('/notifications', [WorkflowController::class, 'notifications']);
    Route::get('/workflows/marks', [WorkflowController::class, 'markWorkflows']);
    Route::get('/audit/security-logs', [WorkflowController::class, 'securityLogs']);
    Route::get('/audit/activity-logs', [WorkflowController::class, 'activityLogs']);
    Route::get('/audit/login-failure-logs', [WorkflowController::class, 'loginFailureLogs']);
    Route::post('/notifications/{notificationId}/read', [WorkflowController::class, 'markNotificationRead']);
    Route::post('/mark-workflows', [WorkflowController::class, 'transitionMarkWorkflow']);
    Route::post('/report-verifications', [WorkflowController::class, 'issueReportVerification']);
    Route::post('/assessments/psra/papers', [AssessmentController::class, 'psraPaperMarks']);
    Route::get('/assessments/psra/dashboard', [AssessmentController::class, 'psraDashboard']);
    Route::post('/assessments/upkk/papers', [AssessmentController::class, 'upkkPaperMarks']);
    Route::get('/assessments/upkk/context', [AssessmentController::class, 'upkkContext']);
    Route::post('/assessments/upkk/grades', [AssessmentController::class, 'upkkGrades']);
    Route::post('/assessments/upkk/practical/{kind}', [AssessmentController::class, 'upkkPracticalMarks']);
    Route::get('/assessments/upkk/practical/{kind}', [AssessmentController::class, 'upkkPracticalIndex']);
    Route::get('/assessments/psra/classes/{classId}', [AssessmentController::class, 'psraReport'])->whereUuid('classId');
    Route::get('/assessments/upkk/classes/{classId}', [AssessmentController::class, 'upkkReport'])->whereUuid('classId');
    Route::post('/character/khalifah-muda', [CharacterAssessmentController::class, 'khalifah']);
    Route::post('/character/sahsiah-ihab', [CharacterAssessmentController::class, 'sahsiah']);
    Route::post('/character/khalifah-muda/component', [CharacterAssessmentController::class, 'component']);
    Route::get('/character/khalifah-muda', [CharacterAssessmentController::class, 'khalifahRecords']);
    Route::get('/character/khalifah-muda/components', [CharacterAssessmentController::class, 'khalifahComponents']);
    Route::get('/character/sahsiah-ihab', [CharacterAssessmentController::class, 'sahsiahRecords']);
    Route::post('/enrollments', [EnrollmentController::class, 'enroll']);
    Route::get('/enrollments', [EnrollmentController::class, 'index']);
    Route::post('/enrollments/promote', [EnrollmentController::class, 'promote']);
    Route::post('/students/transfer', [EnrollmentController::class, 'transfer']);
    Route::get('/licenses', [LicenseController::class, 'index']);
    Route::post('/licenses', [LicenseController::class, 'store']);
    Route::get('/school-modules', [SchoolModuleController::class, 'index']);
    Route::post('/school-modules', [SchoolModuleController::class, 'store']);
    Route::get('/audit/export', [WorkflowController::class, 'auditExport']);
    Route::post('/rph', [RphController::class, 'store']);
    Route::get('/rph', [RphController::class, 'index']);
    Route::post('/rph/weekly/transition', [RphController::class, 'transitionWeekly']);
    Route::post('/rph/{id}/status', [RphController::class, 'status'])->whereUuid('id');
    Route::delete('/rph/{id}', [RphController::class, 'destroy'])->whereUuid('id');
    Route::post('/amal-khair', [AmalKhairController::class, 'store']);
    Route::get('/amal-khair/categories', [AmalKhairController::class, 'categories']);
    Route::get('/amal-khair', [AmalKhairController::class, 'index']);
    Route::post('/timetable/slots/generate', [TimetableController::class, 'generateSlots']);
    Route::get('/timetable/slots', [TimetableController::class, 'slots']);
    Route::get('/timetable/entries', [TimetableController::class, 'entries']);
    Route::get('/timetable/requirements', [TimetableController::class, 'requirements']);
    Route::post('/timetable/slots/update', [TimetableController::class, 'updateSlots']);
    Route::post('/timetable/slots/add', [TimetableController::class, 'addSlot']);
    Route::post('/timetable/slots/delete', [TimetableController::class, 'deleteSlot']);
    Route::post('/timetable/requirements', [TimetableController::class, 'saveRequirement']);
    Route::post('/timetable/requirements/bulk', [TimetableController::class, 'saveRequirements']);
    Route::post('/timetable/entries', [TimetableController::class, 'saveEntry']);
    Route::post('/timetable/generate', [TimetableController::class, 'generateAuto']);
    Route::post('/mark-settings/components', [MarkSettingsController::class, 'store']);
    Route::post('/mark-settings/school', [MarkSettingsController::class, 'school']);
    Route::get('/mark-settings/{kind}', [MarkSettingsController::class, 'index']);
    Route::get('/rph/topics', [RphController::class, 'topics']);
    Route::get('/rph/weekly/{kind}', [RphController::class, 'weekly']);
});

Route::get('/api/report-verifications/{token}', [WorkflowController::class, 'verifyReport']);
Route::get('/sah-laporan/{token}', [ReportVerificationPageController::class, 'show'])->name('report.verify');

Route::get('/ibu-bapa', [ParentPortalController::class, 'loginPage'])->name('parent.login');
Route::post('/ibu-bapa/login', [ParentPortalController::class, 'login'])->name('parent.login.store');
Route::get('/ibu-bapa/portal', [ParentPortalController::class, 'portal'])->name('parent.portal');
Route::post('/ibu-bapa/logout', [ParentPortalController::class, 'logout'])->name('parent.logout');

Route::prefix('api/parent')->group(function () {
    Route::post('/login', [ParentAccessController::class, 'login']);
    Route::get('/report', [ParentAccessController::class, 'report']);
    Route::post('/logout', [ParentAccessController::class, 'logout']);
});
Route::middleware('auth')->post('/api/parent/access-codes', [ParentAccessController::class, 'issue']);
