create table if not exists public.rph_topic_bank (
  id uuid primary key default gen_random_uuid(),
  tahun int not null check (tahun between 1 and 6),
  kod_subjek text not null references public.subjects(kod_subjek) on update cascade,
  nama_subjek text not null,
  tajuk text not null,
  susunan int not null default 999,
  status text not null default 'AKTIF' check (status in ('AKTIF', 'TIDAK_AKTIF')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tahun, kod_subjek, tajuk)
);

create index if not exists rph_topic_bank_lookup_idx
  on public.rph_topic_bank (tahun, kod_subjek, status, susunan);

drop trigger if exists rph_topic_bank_updated_at on public.rph_topic_bank;
create or replace function private.touch_rph_topic_bank_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function private.touch_rph_topic_bank_updated_at() from public, anon, authenticated;

create trigger rph_topic_bank_updated_at
before update on public.rph_topic_bank
for each row execute function private.touch_rph_topic_bank_updated_at();

alter table public.rph_topic_bank enable row level security;

drop policy if exists rph_topic_bank_active_select on public.rph_topic_bank;
create policy rph_topic_bank_active_select
on public.rph_topic_bank for select to authenticated
using ((select private.is_active_user()) and status = 'AKTIF');

drop policy if exists rph_topic_bank_active_write on public.rph_topic_bank;
create policy rph_topic_bank_active_write
on public.rph_topic_bank for all to authenticated
using ((select private.is_active_user()))
with check ((select private.is_active_user()));

revoke all on public.rph_topic_bank from anon;
grant select, insert, update, delete on public.rph_topic_bank to authenticated;

insert into public.rph_topic_bank (tahun, kod_subjek, nama_subjek, tajuk, susunan)
values
  (1,'TILAWAH','Tilawah Al-Quran','Mengenal huruf hijaiyah dan kalimah Al-Quran berbaris seperti kaedah Iqra''',1),
  (1,'TILAWAH','Tilawah Al-Quran','Membaca Juzuk 30',2),
  (1,'TILAWAH','Tilawah Al-Quran','Membaca Juzuk 1',3),
  (1,'TILAWAH','Tilawah Al-Quran','Membaca Juzuk 2',4),
  (1,'TILAWAH','Tilawah Al-Quran','Membaca Juzuk 3',5),
  (1,'TAUHID','Tauhid','Sifat Allah yang wajib dan mustahil: Wujud lawannya Adam',6),
  (1,'FEKAH','Fiqh','Ibadah',7),
  (1,'FEKAH','Fiqh','Taharah',8),
  (1,'FEKAH','Fiqh','Bahagian air',9),
  (1,'FEKAH','Fiqh','Wuduk',10),
  (1,'FEKAH','Fiqh','Istinja''',11),
  (1,'AKHLAK','Akhlak Islami','Doa',12),
  (1,'AKHLAK','Akhlak Islami','Adab dan fadhilat kebersihan diri',13),
  (1,'AKHLAK','Akhlak Islami','Menutup aurat',14),
  (1,'AKHLAK','Akhlak Islami','Adab pergaulan',15),
  (1,'JAWI','Jawi','Huruf-huruf Jawi',16),
  (1,'JAWI','Jawi','Padan huruf vokal',17),
  (1,'JAWI','Jawi','Padan huruf konsonan',18),
  (1,'JAWI','Jawi','Pembentukan suku kata terbuka',19),
  (1,'JAWI','Jawi','Suku kata tertutup vokal a',20),
  (1,'JAWI','Jawi','Suku kata tertutup vokal e pepet',21),
  (2,'TILAWAH','Tilawah Al-Quran','Membaca Juzuk 4 hingga 12',1),
  (2,'TAUHID','Tauhid','Qidam lawannya Huduth',2),
  (2,'TAUHID','Tauhid','Baqa lawannya Fana',3),
  (2,'TAUHID','Tauhid','Mukhalafatuhu lil hawadith lawannya Mumatsalatuhu lil hawadith',4),
  (2,'TAUHID','Tauhid','Qiyamuhu binafsihi lawannya Qiyamuhu bighairihi',5),
  (2,'TAUHID','Tauhid','Wahdaniyyah lawannya Ta''addud',6),
  (2,'TAUHID','Tauhid','Beriman kepada Malaikat',7),
  (2,'TAUHID','Tauhid','Beriman kepada Kitab',8),
  (2,'FEKAH','Fiqh','Najis',9),
  (2,'FEKAH','Fiqh','Hadath',10),
  (2,'FEKAH','Fiqh','Mandi wajib',11),
  (2,'FEKAH','Fiqh','Mandi sunat',12),
  (2,'AKHLAK','Akhlak Islami','Adab makan dan minum',13),
  (2,'AKHLAK','Akhlak Islami','Adab tidur',14),
  (2,'AKHLAK','Akhlak Islami','Adab berkenderaan',15),
  (2,'AKHLAK','Akhlak Islami','Adab di masjid',16),
  (2,'AKHLAK','Akhlak Islami','Adab belajar',17),
  (2,'AKHLAK','Akhlak Islami','Adab dengan mushaf Al-Quran',18),
  (2,'AKHLAK','Akhlak Islami','Adab memelihara harta benda awam',19),
  (2,'JAWI','Jawi','Suku kata tertutup vokal u dan o',20),
  (2,'JAWI','Jawi','Suku kata tertutup vokal i dan e taling',21),
  (2,'JAWI','Jawi','Vokal berganding: ia, iu, ua',22),
  (2,'JAWI','Jawi','Vokal berganding dengan hamzah: ai, au, ui',23),
  (3,'TILAWAH','Tilawah Al-Quran','Membaca Juzuk 13 hingga 21',1),
  (3,'TAUHID','Tauhid','Beriman kepada Rasul',2),
  (3,'TAUHID','Tauhid','Ta''at kepada Rasulullah',3),
  (3,'TAUHID','Tauhid','Nabi Muhammad penutup para nabi',4),
  (3,'TAUHID','Tauhid','Sifat Allah yang wajib dan mustahil',5),
  (3,'FEKAH','Fiqh','Tayammum',6),
  (3,'FEKAH','Fiqh','Azan dan Iqamah',7),
  (3,'FEKAH','Fiqh','Solat fardhu',8),
  (3,'FEKAH','Fiqh','Solat berjemaah',9),
  (3,'SIRAH','Sirah','Nasab Nabi Muhammad',10),
  (3,'SIRAH','Sirah','Peristiwa kelahiran Nabi Muhammad',11),
  (3,'SIRAH','Sirah','Akhlak Nabi Muhammad',12),
  (3,'SIRAH','Sirah','Pekerjaan Nabi Muhammad',13),
  (3,'SIRAH','Sirah','Kehidupan bermasyarakat Nabi Muhammad',14),
  (3,'SIRAH','Sirah','Rumah tangga Nabi Muhammad',15),
  (3,'AKHLAK','Akhlak Islami','Adab menziarahi orang sakit',16),
  (3,'AKHLAK','Akhlak Islami','Adab menziarahi rakan',17),
  (3,'AKHLAK','Akhlak Islami','Bercakap benar',18),
  (3,'AKHLAK','Akhlak Islami','Sabar',19),
  (3,'AKHLAK','Akhlak Islami','Berani',20),
  (3,'AKHLAK','Akhlak Islami','Menepati janji',21),
  (3,'AKHLAK','Akhlak Islami','Malu',22),
  (3,'AKHLAK','Akhlak Islami','Pemaaf',23),
  (3,'JAWI','Jawi','Perayaan kaligrafi Islam (mengenal peralatan)',24),
  (3,'JAWI','Jawi','Membentuk titik',25),
  (3,'JAWI','Jawi','Menulis huruf Jawi: ا، ب، ت، ث',26),
  (3,'JAWI','Jawi','Menulis huruf Jawi: ج، چ، ح، خ',27),
  (3,'JAWI','Jawi','Menulis huruf Jawi: د، ذ',28),
  (3,'IMLAK_KHAT','Khat','Menulis huruf Jawi tunggal mengikut kaedah Khat Naskh',29),
  (3,'IMLAK_KHAT','Khat','Menulis huruf Jawi bersambung mengikut kaedah Khat Naskh',30),
  (3,'IMLAK_KHAT','Imla''','Ism mufrad mudzakkar',31),
  (3,'IMLAK_KHAT','Imla''','Ism muthanna mudzakkar',32),
  (3,'IMLAK_KHAT','Imla''','Ism mufrad muannath',33),
  (3,'IMLAK_KHAT','Imla''','Ism muthanna muannath',34),
  (3,'IMLAK_KHAT','Imla''','Ism jamak mudzakkar salim',35),
  (3,'IMLAK_KHAT','Imla''','Ism jamak muannath salim',36),
  (4,'TILAWAH','Tilawah Al-Quran','Membaca Juzuk 22 hingga 29',1),
  (4,'TAUHID','Tauhid','Qudrat lawannya ''Ajz',2),
  (4,'TAUHID','Tauhid','Iradat lawannya Karahah',3),
  (4,'TAUHID','Tauhid','Ilmu lawannya Jahl',4),
  (4,'TAUHID','Tauhid','Hayat lawannya Maut',5),
  (4,'TAUHID','Tauhid','Sam'' lawannya Samam',6),
  (4,'TAUHID','Tauhid','Basar lawannya ''Ama',7),
  (4,'TAUHID','Tauhid','Kalam lawannya Bakam',8),
  (4,'TAUHID','Tauhid','Sifat wajib, mustahil dan harus bagi Rasul',9),
  (4,'TAUHID','Tauhid','Beriman kepada hari qiamat',10),
  (4,'FEKAH','Fiqh','Solat Jumaat',11),
  (4,'FEKAH','Fiqh','Khutbah Jumaat',12),
  (4,'FEKAH','Fiqh','Solat sunat',13),
  (4,'FEKAH','Fiqh','Solat jamak dan qasar',14),
  (4,'SIRAH','Sirah','Pelantikan Nabi sebagai Rasul',15),
  (4,'SIRAH','Sirah','Hijrah ke Habsyah dan Taif',16),
  (4,'SIRAH','Sirah','Israk dan Mikraj',17),
  (4,'SIRAH','Sirah','Peristiwa Hijrah ke Madinah',18),
  (4,'SIRAH','Sirah','Asas negara Islam pertama: Pembinaan Masjid',19),
  (4,'SIRAH','Sirah','Asas negara Islam kedua: Persaudaraan dan perpaduan ummah',20),
  (4,'SIRAH','Sirah','Asas negara Islam ketiga: Sahifah Madinah',21),
  (4,'SIRAH','Sirah','Pentadbiran Khalifah pertama dalam kerajaan Islam',22),
  (4,'SIRAH','Sirah','Pembukaan Kota Makkah',23),
  (4,'AKHLAK','Akhlak Islami','Tolong-menolong dalam perkara kebaikan',24),
  (4,'AKHLAK','Akhlak Islami','Bertanggungjawab',25),
  (4,'AKHLAK','Akhlak Islami','Adab berjalan',26),
  (4,'AKHLAK','Akhlak Islami','Adab bermain',27),
  (4,'AKHLAK','Akhlak Islami','Adab berkomunikasi',28),
  (4,'AKHLAK','Akhlak Islami','Adab berjiran',29),
  (4,'AKHLAK','Akhlak Islami','Sifat mahmudah',30),
  (4,'AKHLAK','Akhlak Islami','Sifat mazmumah',31),
  (4,'JAWI','Jawi','Menulis huruf Jawi: ر، ز',32),
  (4,'JAWI','Jawi','Menulis huruf Jawi: س، ش',33),
  (4,'JAWI','Jawi','Menulis huruf Jawi: ص، ض',34),
  (4,'JAWI','Jawi','Menulis huruf Jawi: ط، ظ',35),
  (4,'JAWI','Jawi','Menulis huruf Jawi: ع، غ',36),
  (4,'JAWI','Jawi','Menulis huruf Jawi: ف',37),
  (4,'JAWI','Jawi','Menulis huruf Jawi: ق',38),
  (4,'IMLAK_KHAT','Khat','Menulis huruf Jawi tunggal dan bersambung mengikut Khat Naskh',39),
  (4,'IMLAK_KHAT','Imla''','Hamzah di awal, tengah dan akhir kalimah',40),
  (4,'IMLAK_KHAT','Imla''','Hamzah ditulis di atas huruf wau',41),
  (4,'IMLAK_KHAT','Imla''','Alif Lam Qamariyyah',42),
  (4,'IMLAK_KHAT','Imla''','Alif Lam Syamsiyyah',43),
  (4,'BAHASA_ARAB','Bahasa Arab','الأعداد والأرقام: 301–400',44),
  (4,'BAHASA_ARAB','Bahasa Arab','المراكب والمواصلات',45),
  (4,'BAHASA_ARAB','Bahasa Arab','أسماء الإشارة',46),
  (4,'BAHASA_ARAB','Bahasa Arab','أسماء الاستفهام',47),
  (4,'BAHASA_ARAB','Bahasa Arab','الجملة الفعلية',48),
  (4,'BAHASA_ARAB','Bahasa Arab','القصة المختارة: زيارة العم – إما المؤمنون إخوة',49),
  (4,'BAHASA_ARAB','Bahasa Arab','الحوار في المكتبة',50),
  (4,'BAHASA_ARAB','Bahasa Arab','الحوار في الملعب',51),
  (5,'TILAWAH','Tilawah Al-Quran','Mad dan pembahagiannya',1),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Asli Kalimi',2),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Asli Harfi',3),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Wajib Muttasil',4),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Jaiz Munfasil',5),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Badal',6),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Silah Tawilah',7),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Farq',8),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Ta''zim',9),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Lazim Kalimi Muthaqqal',10),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Lazim Kalimi Mukhaffaf',11),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Lazim Harfi Muthaqqal',12),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Lazim Harfi Mukhaffaf',13),
  (5,'TILAWAH','Tilawah Al-Quran','Mad ''Aridh Lissukun',14),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Lin',15),
  (5,'TILAWAH','Tilawah Al-Quran','Mad ''Iwadh',16),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Tamkin',17),
  (5,'TILAWAH','Tilawah Al-Quran','Mad Silah Qasirah',18),
  (5,'TILAWAH','Tilawah Al-Quran','Tingkatan Mad',19),
  (5,'TILAWAH','Tilawah Al-Quran','Waqaf',20),
  (5,'TAUHID','Tauhid','Beriman kepada qadar dan qada',21),
  (5,'TAUHID','Tauhid','Al-Asma'' al-Husna 1–50',22),
  (5,'FEKAH','Fiqh','Solat orang sakit',23),
  (5,'FEKAH','Fiqh','Solat dalam kenderaan',24),
  (5,'FEKAH','Fiqh','Solat sunat dua hari raya',25),
  (5,'FEKAH','Fiqh','Pengurusan jenazah',26),
  (5,'FEKAH','Fiqh','Puasa',27),
  (5,'FEKAH','Fiqh','Zakat',28),
  (5,'SIRAH','Sirah','Konsep jihad',29),
  (5,'SIRAH','Sirah','Jenis-jenis jihad',30),
  (5,'SIRAH','Sirah','Peperangan zaman Nabi',31),
  (5,'SIRAH','Sirah','Perang Badr',32),
  (5,'SIRAH','Sirah','Perang Uhud',33),
  (5,'SIRAH','Sirah','Perang Khandaq',34),
  (5,'SIRAH','Sirah','Perjanjian dengan Bani Nadhir dan Quraizah',35),
  (5,'SIRAH','Sirah','Perjanjian Hudaibiyah',36),
  (5,'AKHLAK','Akhlak Islami','Adab berjual beli',37),
  (5,'AKHLAK','Akhlak Islami','Adab dalam majlis',38),
  (5,'AKHLAK','Akhlak Islami','Adab kepada pemimpin',39),
  (5,'AKHLAK','Akhlak Islami','Sifat mahmudah: zuhud, sabar, syukur, ikhlas',40),
  (5,'AKHLAK','Akhlak Islami','Sifat mazmumah: ghadab, hasad, bakhil, hubb al-jah',41),
  (5,'JAWI','Jawi','Menulis huruf Jawi: ك، ل، م، ن، و، ه، لا، ء، ي',42),
  (5,'IMLAK_KHAT','Khat','Menulis huruf Jawi tunggal dan bersambung mengikut Khat Naskh',43),
  (5,'IMLAK_KHAT','Imla''','Alif Lam Layyinah di tengah kalimah',44),
  (5,'IMLAK_KHAT','Imla''','Alif Lam Layyinah di akhir kalimah: alif maddah',45),
  (5,'IMLAK_KHAT','Imla''','Alif Lam Layyinah di akhir kalimah: alif maqsurah',46),
  (5,'IMLAK_KHAT','Imla''','Al-Ta'' al-Maftuhah',47),
  (5,'IMLAK_KHAT','Imla''','Al-Ta'' al-Marbutah',48),
  (5,'BAHASA_ARAB','Bahasa Arab','الأعداد والأرقام: 401–500',49),
  (5,'BAHASA_ARAB','Bahasa Arab','الضمائر',50),
  (5,'BAHASA_ARAB','Bahasa Arab','الرحلة إلى شاطئ البحر',51),
  (5,'BAHASA_ARAB','Bahasa Arab','الطيور والحشرات',52),
  (5,'BAHASA_ARAB','Bahasa Arab','أدوات الاتصالية الحديثة',53),
  (5,'BAHASA_ARAB','Bahasa Arab','الرحلة إلى حديقة الحيوانات',54),
  (5,'BAHASA_ARAB','Bahasa Arab','حروف النفي وحروف النهي – لا الناهية',55),
  (5,'BAHASA_ARAB','Bahasa Arab','حروف الجر',56),
  (5,'BAHASA_ARAB','Bahasa Arab','الزيارة إلى المستشفى',57),
  (5,'BAHASA_ARAB','Bahasa Arab','الفاعل',58),
  (5,'BAHASA_ARAB','Bahasa Arab','المفعول به',59),
  (5,'BAHASA_ARAB','Bahasa Arab','الفعل الثلاثي المزيد بحرف واحد',60),
  (5,'BAHASA_ARAB','Bahasa Arab','الزيارة إلى المحلات التجارية',61),
  (6,'TILAWAH','Tilawah Al-Quran','Idgham Mutamathilain',1),
  (6,'TILAWAH','Tilawah Al-Quran','Idgham Mutaqaribain',2),
  (6,'TILAWAH','Tilawah Al-Quran','Idgham Mutajanisain',3),
  (6,'TILAWAH','Tilawah Al-Quran','Hukum Ra'': tafkhim, tarqiq, dua wajah',4),
  (6,'TILAWAH','Tilawah Al-Quran','Hukum tanwin bertemu hamzah wasal',5),
  (6,'TILAWAH','Tilawah Al-Quran','Saktah',6),
  (6,'TILAWAH','Tilawah Al-Quran','Imalah',7),
  (6,'TILAWAH','Tilawah Al-Quran','Naql',8),
  (6,'TILAWAH','Tilawah Al-Quran','Tas-hil',9),
  (6,'TILAWAH','Tilawah Al-Quran','Ibdal',10),
  (6,'TILAWAH','Tilawah Al-Quran','Isymam',11),
  (6,'TILAWAH','Tilawah Al-Quran','Raum',12),
  (6,'TILAWAH','Tilawah Al-Quran','Bacaan Al-Quran',13),
  (6,'TAUHID','Tauhid','Perkara sam''iyyat',14),
  (6,'TAUHID','Tauhid','Mukjizat',15),
  (6,'TAUHID','Tauhid','Irhas, karamah, ma''unah, istidraj, ihanah dan sihir',16),
  (6,'TAUHID','Tauhid','Syirik dan perkara khurafat',17),
  (6,'TAUHID','Tauhid','Al-Asma'' al-Husna 51–99',18),
  (6,'FEKAH','Fiqh','Haji dan Umrah',19),
  (6,'FEKAH','Fiqh','Sembelihan',20),
  (6,'FEKAH','Fiqh','Muamalat',21),
  (6,'FEKAH','Fiqh','Munakahat',22),
  (6,'FEKAH','Fiqh','Faraid',23),
  (6,'FEKAH','Fiqh','Jinayat',24),
  (6,'SIRAH','Sirah','Kejatuhan negara Islam',25),
  (6,'SIRAH','Sirah','Sahabat Khulafa'' al-Rasyidin',26),
  (6,'SIRAH','Sirah','Ahl al-Bait',27),
  (6,'SIRAH','Sirah','Sahabat Nabi yang mendapat jaminan syurga',28),
  (6,'AKHLAK','Akhlak Islami','Menziarahi jenazah',29),
  (6,'AKHLAK','Akhlak Islami','Menziarahi kubur',30),
  (6,'AKHLAK','Akhlak Islami','Sifat mahmudah: tawakkal, mahabbah, redha, zikrul maut',31),
  (6,'AKHLAK','Akhlak Islami','Sifat mazmumah: hubb al-dunya, takbur, ujub, riya''',32),
  (6,'JAWI','Jawi','Menulis huruf Jawi tunggal dan bersambung mengikut Khat Thuluth',33),
  (6,'IMLAK_KHAT','Khat','Menulis huruf Jawi mengikut Khat Thuluth',34),
  (6,'IMLAK_KHAT','Khat','Menulis tanda baris Khat Naskh dan Thuluth',35),
  (6,'IMLAK_KHAT','Khat','Perbandingan ciri-ciri huruf',36),
  (6,'IMLAK_KHAT','Khat','Perbandingan ciri-ciri kalimah',37),
  (6,'BAHASA_ARAB','Bahasa Arab','الأعداد والأرقام: 600–2000',38),
  (6,'BAHASA_ARAB','Bahasa Arab','أوزان الأفعال',39),
  (6,'BAHASA_ARAB','Bahasa Arab','القصة المختارة: بر الوالدين',40),
  (6,'BAHASA_ARAB','Bahasa Arab','تصريف الأفعال',41),
  (6,'BAHASA_ARAB','Bahasa Arab','المبتدأ والخبر',42),
  (6,'BAHASA_ARAB','Bahasa Arab','القصة المختارة: الأسرة السعيدة',43),
  (6,'BAHASA_ARAB','Bahasa Arab','حروف العطف',44),
  (6,'BAHASA_ARAB','Bahasa Arab','الكلمات المتضادة',45),
  (6,'BAHASA_ARAB','Bahasa Arab','القصة المختارة: اللعب بالنار',46),
  (6,'BAHASA_ARAB','Bahasa Arab','الحوار',47),
  (6,'BAHASA_ARAB','Bahasa Arab','الحكم والأمثال المختارة',48)
on conflict (tahun, kod_subjek, tajuk) do update set
  nama_subjek = excluded.nama_subjek,
  susunan = excluded.susunan,
  status = 'AKTIF',
  updated_at = now();
